<a href="https://colab.research.google.com/github/dl-colman/exercise-1/blob/main/Exercise_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise 1-2 Softmax Activation

### Pip Install the nnfs library

In [1]:
!pip install nnfs

### Import libraries

In [2]:
import numpy as np 
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

### Create Dataset

In [3]:
X, y = spiral_data(100, 3)   

<img width="450px" src="https://www.annytab.com/wp-content/uploads/2019/12/spirals.png">

### Dense Layer

In [4]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

### Rectifier Linear (ReLU) Class

In [6]:
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

# Complete The Softmax Class
<img src="https://icecube-eu-303.icedrive.io/download?p=Ga83uYEY8zeaz.NZODP0cGE9qU5hCb1S8axWYqVx_2f5JxR01IWMQy22sJkUJClxbqxkUZEacg7EY1ASnG_NjyASR_euvGcqp8XEcVHXfRfcSwcAlFwJWPLm_DXfJu7xrr9kNCAr.oBx9nQAbTrT0f92wlRD2CaqO.wEfOoYNMU00afRqsvGmsPpyFGstkW8">

In [17]:
class Activation_Softmax:
  """ Use us! np.exp(); np.sum() 
  Do not forget to add to np.sum() 
      axis=1, keepdims=True"""
  def forward(self, inputs):
    safe_inputs = inputs - np.max(inputs, axis=1, keepdims=True)
    exp_values = # *** YOUR CODE HERE ***
    probabilities = # *** YOUR CODE HERE ***
    # *** YOUR CODE HERE ***

Test Your Code

In [18]:
dense1 = Layer_Dense(2,3)
activation1 = Activation_ReLU()

dense2 = Layer_Dense(3, 3)
activation2 = Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.33333588 0.33332154 0.33334258]
 [0.33333936 0.33330533 0.3333553 ]
 [0.33327898 0.33335957 0.33336148]
 [0.33327773 0.33334932 0.33337292]]
